# yaml-language-server: $schema=https://github.com/KeisukeYamashita/commitlint-rs/releases/download/v0.2.2/schema.json
rules:
  description-format:
    format: ^[a-z]
    level: error
  description-max-length:
    length: 72
    level: error
  footers-empty:
    level: ignore
  type:
    options:
      - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
