rules:
  description-format:
    level: error
    format: ^[A-Z].*$ # Must start with a capital letter
  footers-empty:
    level: ignore
  scope:
    optional: true
    options:
      - config
      - flake
      - flake/templates
      - scripts
  type:
    level: error
    options:
      - build # Build system or dependency changes
      - chore # Other non-src/test changes
      - ci # CI configuration changes
      - docs # Documentation changes
      - feat # New feature
      - fix # Bug fix
      - perf # Performance improvement
      - refactor # Code change (no bug fix/feature)
      - revert # Revert previous commit
      - style # Non-functional code changes
      - test # Test addition or correction
  type-format:
    level: error
    format: ^[a-z].*$ # Must start with lowercase letter
