default_stages:
  - pre-commit
repos:
  - hooks:
      - args:
          - --edit
          - ./.git/COMMIT_EDITMSG
        entry: commitlint
        id: commitlint-rs
        language: system
        name: commitlint-rs
        pass_filenames: false
        require_serial: true
        stages:
          - prepare-commit-msg
      - entry: editorconfig-checker
        id: editorconfig-checker
        language: system
        name: editorconfig-checker
      - args:
          - --fail-on-change
          - --no-cache
        entry: treefmt
        id: treefmt
        language: system
        name: treefmt
    repo: local
