concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  CACHIX_CACHE_NAME: haruno
jobs:
  flake:
    name: Flake
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true
      - name: Install and setup cachix
        uses: cachix/cachix-action@v15
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_CACHE_NAME }}
      - name: Install nix-fast-build
        run: nix profile install nixpkgs#nix-fast-build
      - name: Build devShells
        run: nix-fast-build --skip-cached --no-nom --flake ".#devShells"
name: Build
on:
  pull_request: {}
  push: {}
