concurrency:
  cancel-in-progress: true
  group: ${{ github.action }}-${{ github.ref }}
jobs:
  flake-checker:
    name: Flake Checker
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run flake-checker-action
        uses: DeterminateSystems/flake-checker-action@v9
        with:
          send-statistics: false
name: Check
on:
  pull_request: {}
  push: {}
